name: main

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '.golangci.yml'
      - '.github/workflows/main.yml'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 1
      - name: go test
        # issue: pattern ./...: directory prefix . does not contain main module or its selected dependencies
        # see https://github.com/golangci/golangci-lint/issues/2654
        # or, maybe, just maybe, I simply forgot to add actions/checkout like a dummy
        run: go test -v ./... # -coverprofile=coverage.txt -covermode=atomic
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3