name: main

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '.golangci.yml'
      - '.github/workflows/main.yml'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: go test
        run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3